ecommerce/apps/travel/urls.py
from django.urls import path

from .views import (
    company,
    places,
    service,
    travel,
    public,
)
app_name = "travel"

urlpatterns = [

    path("",public.home,name="home_travel"),
    path("travel/user/company/", company.company_user, name="company_user"),
    path("travel/company/",company.list,name="company_list"),
    path("travel/company/add/", company.add, name="company_add"),
    path("travel/company/update/<slug:slug>/", company.update, name="company_update"),
    path("travel/company/delete/<slug:slug>/", company.delete, name="company_delete"),
    path("travel/company/<slug:slug>/detail", company.detail, name="company_detail"),


    path("travel/places/add/", places.add, name="places_add"),
    path("travel/places/update/<slug:slug>/", places.update, name="places_update"),
    path("travel/places/delete/<slug:slug>/", places.delete, name="places_delete"),
    path("travel/places/",places.list,name="places_list"),
    path("travel/places/<slug:slug>/detail", places.detail, name="places_detail"),

    path("travel/service/add/", service.add, name="service_add"),
    path("travel/service/<slug:slug>/detail", service.detail, name="service_detail"),
    path("travel/service/update/<slug:slug>/", service.update, name="service_update"),
    path("travel/service/delete/<slug:slug>/", service.delete, name="service_delete"),
    path("travel/service/", service.list, name="service_list"),

    path("travel/service/<str:service_id>/travel/add/", travel.add, name="travel_add"),
    path("travel/service/<str:service_id>/travel/<slug:slug>/detail", travel.detail, name="travel_detail"),
    path("travel/service/<str:service_id>/travel/update/<slug:slug>/", travel.update, name="travel_update"),
    path("travel/service/<str:service_id>/travel/delete/<slug:slug>/", travel.delete, name="travel_delete"),
    path("travel/service/<str:service_id>/travel/", travel.list, name="travel_list"),

    # path("mycompany",views.CompanyView.as_view(),name="mycompany"),
    # path("<slug:slug>", views.product_detail, name="product_detail"),
    # path("shop/<slug:category_slug>/", views.category_list, name="category_list"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ecommerce.apps.travel.urls", namespace="travel")),
    path("", include("ecommerce.apps.catalogue.urls", namespace="catalogue")),
    path("checkout/", include("ecommerce.apps.checkout.urls", namespace="checkout")),
    path("basket/", include("ecommerce.apps.basket.urls", namespace="basket")),
    path("account/", include("ecommerce.apps.account.urls", namespace="account")),
    path("orders/", include("ecommerce.apps.orders.urls", namespace="orders")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/apps/travel/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordResetForm,
    SetPasswordForm
)

from .models import (
    Company,
    Place,
    Service,
    Travel
)


class CompanyForm(forms.ModelForm):
    name = forms.CharField(
        label='Nombre de la empresa',
        min_length=4,
        max_length=255,
        help_text='Required',
    )

    razon_social = forms.CharField(
        label='Razon Social',
        min_length=1,
        max_length=255,
        help_text='Required')

    nit = forms.CharField(
        label='NIT',
        min_length=1,
        max_length=50,
        help_text='Required')

    class Meta:
        model = Company
        fields = ('name','razon_social','nit')

    #
    # def clean_nit(self):
    #     nit = self.cleaned_data['nit'].upper().strip()
    #     r = Company.objects.filter(nit=nit)
    #     if r.count():
    #         raise forms.ValidationError("El NIT ya existe.")
    #     return nit

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Nombre de la empresa'})
        self.fields['razon_social'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Razon Social'})
        self.fields['nit'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'NIT'})


class PlaceForm(forms.ModelForm):

    class Meta:
        model = Place
        fields = ('name','address','img_l','latitude','longitude',)
        widgets={
            'img_l': forms.FileInput(attrs={'style': 'display: block;', 'class': 'form-control', 'required': False, })
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Nombre del lugar'})
        self.fields['address'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Direccion'})
        self.fields['latitude'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'GPS' ,'readonly':'true'})
        self.fields['longitude'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'GPS','readonly':'true'})


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = (
            'name',
            'origin',
            'destination',
            'price',
            'description',
            'img_l',
        )
        widgets={
            'name' : forms.TextInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
            'origin': forms.Select(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
            'destination': forms.Select(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
            'price': forms.NumberInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
            'description': forms.Textarea(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
            'img_l': forms.FileInput(attrs={'style': 'display: block;', 'class': 'form-control', })
        }
import datetime

class TravelForm(forms.ModelForm):
    # time_departure = forms.DateTimeField(initial=datetime.date.today)
    class Meta:
        model = Travel
        fields = (
            'service',
            'time_departure',
            'time_arrival_destination',
            'time_departure_return',
            'time_arrival_return',
            'travel_type',
            'passengers_limit',
        )
        widgets={
        'service' : forms.HiddenInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
        'time_departure' : forms.DateTimeInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
        'time_arrival_destination' : forms.DateTimeInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
        'time_departure_return' : forms.DateTimeInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
        'time_arrival_return' : forms.DateTimeInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
        'travel_type' : forms.Select(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
        'passengers_limit' : forms.NumberInput(attrs={'style': 'display: block;', 'class': 'form-control mb-3' }),
        }

ecommerce/apps/travel/views/company.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Company
from ..forms import CompanyForm
from django.contrib.auth.decorators import login_required
from django.views import View


from django.http import HttpResponse
@login_required
def company_user(request):
    try:
        company  = request.user.company
        return render(request, "travel/company/company.html", {"company": company,"services": company.services.all()})
    except Company.DoesNotExist:
        company = None
    return render(request, "travel/company/company.html", {"company": False ,"services": [] })


@login_required
def add(request):
    if request.method == "POST":
        company_form = CompanyForm(data=request.POST)
        if company_form.is_valid():
            company = company_form.save(commit=False)
            company.user = request.user
            company.save()
            return HttpResponseRedirect(reverse("travel:company_user"))
        else:
            return render(request, "travel/company/add.html", {"form": company_form})
    company_form = CompanyForm()
    return render(request,"travel/company/add.html",{"form": company_form})


@login_required
def update(request,slug=None):
    company = get_object_or_404(Company, id=slug)
    if request.method == "POST":
        company_form = CompanyForm(data=request.POST,instance=company)
        if company_form.is_valid():
            company_form.save()
            return HttpResponseRedirect(reverse("travel:company_user"))
        else:
            return render(request,"travel/company/update.html",{"form": company_form ,'company':company})

    company_form = CompanyForm(instance=company)
    return render(request,"travel/company/update.html",{"form": company_form ,'company':company})

@login_required
def detail(request,slug):
    company = get_object_or_404(Company, id=slug)
    return render(request, "travel/company/company.html", {"company": company, "services": company.services.all()})


@login_required
def delete(request,slug):
    company = get_object_or_404(Company, id=slug)
    if request.method == "POST":
        company.delete()
        return render(request,"travel/company/delete.html")
    return render(request, "travel/company/delete.html", {"company":company})


@login_required
def list(request):
    companies = Company.objects.all().order_by("name")
    return render(request,"travel/company/list.html",{"companies": companies})

ecommerce/apps/travel/views/places.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Place
from ..forms import PlaceForm
from django.contrib.auth.decorators import login_required

@login_required
def add(request):
    if request.method == "POST":
        place_form = PlaceForm(request.POST, request.FILES)
        if place_form.is_valid():
            place_form.save()
            return HttpResponseRedirect(reverse("travel:places_list"))
        else:
            return render(request, "travel/places/add.html", {"form": place_form})
    place_form = PlaceForm()
    return render(request,"travel/places/add.html",{"form": place_form})


@login_required
def update(request,slug=None):
    place = get_object_or_404(Place, id=slug)
    if request.method == "POST":
        place_form = PlaceForm(data=request.POST,files=request.FILES,instance=place)
        if place_form.is_valid():
            place_form.save()
            return HttpResponseRedirect(reverse("travel:places_list"))
        else:
            return render(request,"travel/places/update.html",{"form": place_form ,'place':place})

    place_form = PlaceForm(instance=place)
    return render(request,"travel/places/update.html",{"form": place_form ,'place':place})

@login_required
def detail(request,slug):
    place = get_object_or_404(Place, id=slug)
    return render(request, "travel/places/detail.html", {"place": place})


@login_required
def delete(request,slug):
    place = get_object_or_404(Place, id=slug)
    if request.method == "POST":
        place.delete()
        return render(request,"travel/places/delete.html")
    return render(request, "travel/places/delete.html", {"place":place})


@login_required
def list(request):
    places = Place.objects.all().order_by("name")
    return render(request,"travel/places/list.html",{"places": places})

ecommerce/apps/travel/views/public.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Service,Travel
from ..forms import TravelForm
from django.contrib.auth.decorators import login_required


def home(request):
    services = Service.objects.all().order_by("name")
    return render(request,"public/travel/home.html",{"services": services})

ecommerce/apps/travel/views/service.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Service
from ..forms import ServiceForm
from django.contrib.auth.decorators import login_required

@login_required
def add(request):
    if request.method == "POST":
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            service = form.save(commit=False)
            service.company = request.user.company
            service.save()
            return HttpResponseRedirect(reverse("travel:company_user"))
        else:
            return render(request, "travel/service/add.html", {"form": form})
    form = ServiceForm()
    return render(request,"travel/service/add.html",{"form": form})

@login_required
def detail(request,slug):
    service = get_object_or_404(Service,id=slug)
    return render(request,"travel/service/detail.html",{"service": service,"travels":service.travels.all()})



@login_required
def update(request,slug):

    service = get_object_or_404(Service,id=slug,company=request.user.company)
    if request.method == "POST":
        form = ServiceForm(request.POST, request.FILES,instance=service)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("travel:service_detail",kwargs={'slug':service.id}))
        else:
            return render(request, "travel/service/update.html", {"form": form , "service":service})
    form = ServiceForm(instance=service)
    return render(request,"travel/service/update.html",{"form": form , "service":service})


@login_required
def delete(request,slug):
    service = get_object_or_404(Service, id=slug)
    if request.method == "POST":
        service.delete()
        return render(request, "travel/service/delete.html")
    return render(request, "travel/service/delete.html", {"service":service})



@login_required
def list(request):
    services = Service.objects.all().order_by("name")
    return render(request,"travel/service/list.html",{"services": services})

ecommerce/apps/travel/views/travel.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Service,Travel
from ..forms import TravelForm
from django.contrib.auth.decorators import login_required
import datetime
@login_required
def add(request,service_id):
    service = get_object_or_404(Service,id=service_id)
    if request.method == "POST":
        form = TravelForm(request.POST, request.FILES)
        if form.is_valid():
            travel = form.save(commit=False)
            travel.available_seats = travel.passengers_limit
            travel.save()
            return HttpResponseRedirect(reverse("travel:service_detail" , kwargs={'slug':service.id}))
        else:
            return render(request, "travel/travel/add.html", {"form": form , "service":service})

    travel = Travel(
        service = service ,
        time_departure = datetime.date.today ,
        time_arrival_destination = datetime.date.today ,
        time_departure_return = datetime.date.today ,
        time_arrival_return =  datetime.date.today,
        travel_type = "V" ,
        passengers_limit = 100 ,
    )
    form = TravelForm(instance=travel)
    return render(request,"travel/travel/add.html",{"form": form , "service":service})

@login_required
def detail(request,slug,service_id):
    service = get_object_or_404(Service,id=service_id)
    travel = get_object_or_404(Travel,id=slug)
    return render(request,"travel/travel/detail.html",{"travel": travel,"service":service})



@login_required
def update(request,slug,service_id):
    service = get_object_or_404(Service,id=service_id)
    travel = get_object_or_404(Travel,id=slug,service=service)
    if request.method == "POST":
        form = TravelForm(request.POST, request.FILES,instance=travel)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("travel:travel_detail",kwargs={'slug':travel.id,'service_id':service.id }))
        else:
            return render(request,"travel/travel/update.html",{"form": form , "travel":travel,"service":service })
    form = TravelForm(instance=travel)
    return render(request,"travel/travel/update.html",{"form": form , "travel":travel,"service":service })


@login_required
def delete(request,slug,service_id):
    service = get_object_or_404(Service, id=service_id)
    travel = get_object_or_404(Travel, id=slug)
    if request.method == "POST":
        travel.delete()
        return render(request, "travel/travel/delete.html")
    return render(request, "travel/travel/delete.html", {"travel":travel,"service":service })



@login_required
def list(request):
    travels = Travel.objects.all().order_by("name")
    return render(request,"travel/travel/list.html",{"travels": travels})

templates/travel/service/detail.html
{% extends "./base.html" %}
{% block sub_content %}


<div class="row">

    <div class="col-12">

        <h2> Servicio: {{service.name}} </h2>
        {%if service.origin%}
        <div class="">Lugar de Partida: <a href="{% url 'travel:places_detail' slug=service.origin.id %}"> {{service.origin}}</a>

        {%endif%}
         {%if service.destination %}
     <div class="">Lugar de Destino: <a href="{% url 'travel:places_detail' slug=service.destination.id %}"> {{service.destination}}</a>
        {%endif%}


            <div class="d-flex justify-content-end">

                          <a class="nav-link dropdown-toggle text-reset" href="#" id="companyDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                              <svg class="svg-icon" width="22" height="22" viewBox="0 0 20 20">
							    <path d="M3.936,7.979c-1.116,0-2.021,0.905-2.021,2.021s0.905,2.021,2.021,2.021S5.957,11.116,5.957,10
								S5.052,7.979,3.936,7.979z M3.936,11.011c-0.558,0-1.011-0.452-1.011-1.011s0.453-1.011,1.011-1.011S4.946,9.441,4.946,10
								S4.494,11.011,3.936,11.011z M16.064,7.979c-1.116,0-2.021,0.905-2.021,2.021s0.905,2.021,2.021,2.021s2.021-0.905,2.021-2.021
								S17.181,7.979,16.064,7.979z M16.064,11.011c-0.559,0-1.011-0.452-1.011-1.011s0.452-1.011,1.011-1.011S17.075,9.441,17.075,10
								S16.623,11.011,16.064,11.011z M10,7.979c-1.116,0-2.021,0.905-2.021,2.021S8.884,12.021,10,12.021s2.021-0.905,2.021-2.021
								S11.116,7.979,10,7.979z M10,11.011c-0.558,0-1.011-0.452-1.011-1.011S9.442,8.989,10,8.989S11.011,9.441,11.011,10
								S10.558,11.011,10,11.011z"></path>
						    </svg>
                          </a>
                           <div class="dropdown-menu rounded-0" aria-labelledby="companyDropdown">
                            <div class="card border-0">
                              <div class="card-body">
                                <ul class="list-group list-group-flush dropdown-account-link">
                                    <a href="{% url 'travel:service_update' slug=service.id %}" class="text-reset small list-group-item p-0 pb-O border-0 dropdown-account-link">Actualizar</a>
                                    <a href="{% url 'travel:service_delete' slug=service.id %}" class="text-reset small list-group-item p-0 pb-O border-0 dropdown-account-link">Eliminar</a>
                                </ul>
                              </div>
                            </div>
                           </div>
                      </div>

        <div class="card card-service">
          <div>
              <img src="/media/{{service.img_l}}" class="card-img-top" alt="...">
              <div class="card-service-title ">
                  {{service.name}}
              </div>
          </div>

          <div class="card-body">
              <div>{{service.description}}</div>
              <div>{{service.price}}$ por persona</div>
          </div>
            <div class="card-footer">
                <a href="{% url 'travel:travel_add' service_id=service.id %}" class="btn btn-primary"> Nuevo viaje</a>

          </div>
        </div>
    </div>
    <div class="col-lg-12">
          <div class="card">
              <div class="card-body">
                  {% if not travels %}
                    <div>Aun no hay Viajes para este servicio</div>
                  {% else %}

                     <table class="table">
                       <thead>
                        <tr>
                            <th scope="col">Fecha y hora de partida</th>
                            <th scope="col">Fecha y hora de llegada al destino </th>
                            <th scope="col">Fecha y hora de retorno</th>
                            <th scope="col">Fecha y hora de llegada al inicio</th>
                            <th scope="col">Tipo de viaje</th>
                            <th scope="col">Cantidad de asientos disponibles</th>
                            <th scope="col">Limite</th>
                            <th scope="col">Valoracion</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Acción</th>
                        </tr>
                       </thead>
                        <tbody>
                            {% for travel in travels %}
                            <tr>
                                <td>
                                    <a href="{% url 'travel:travel_detail' slug=travel.id service_id=service.id %}">{{travel.time_departure}}</a>
                                </td>
                                <td>{{travel.time_arrival_destination}}</td>
                                <td>{{travel.time_departure_return}}</td>
                                <td>{{travel.time_arrival_return}}</td>
                                <td>{{travel.travel_type}}</td>
                                <td>{{travel.available_seats}}</td>
                                <td>{{travel.passengers_limit}}</td>
                                <td>{{travel.rating}}</td>
                                <td>{{travel.is_active}}</td>
                                <td>

                                    <a class="btn btn-small" href="{% url 'travel:travel_update' slug=travel.id service_id=service.id%}"  title="Editar">
                                    <svg class="svg-icon" width="18" height="18" viewBox="0 0 20 20">
                                        <path fill="blue" d="M19.404,6.65l-5.998-5.996c-0.292-0.292-0.765-0.292-1.056,0l-2.22,2.22l-8.311,8.313l-0.003,0.001v0.003l-0.161,0.161c-0.114,0.112-0.187,0.258-0.21,0.417l-1.059,7.051c-0.035,0.233,0.044,0.47,0.21,0.639c0.143,0.14,0.333,0.219,0.528,0.219c0.038,0,0.073-0.003,0.111-0.009l7.054-1.055c0.158-0.025,0.306-0.098,0.417-0.211l8.478-8.476l2.22-2.22C19.695,7.414,19.695,6.941,19.404,6.65z M8.341,16.656l-0.989-0.99l7.258-7.258l0.989,0.99L8.341,16.656z M2.332,15.919l0.411-2.748l4.143,4.143l-2.748,0.41L2.332,15.919z M13.554,7.351L6.296,14.61l-0.849-0.848l7.259-7.258l0.423,0.424L13.554,7.351zM10.658,4.457l0.992,0.99l-7.259,7.258L3.4,11.715L10.658,4.457z M16.656,8.342l-1.517-1.517V6.823h-0.003l-0.951-0.951l-2.471-2.471l1.164-1.164l4.942,4.94L16.656,8.342z"></path>
                                    </svg>
                                    </a>
                                     <a class="btn btn-small"  title="Eliminar" href="{% url 'travel:travel_delete' slug=travel.id service_id=service.id%}">
                                       <svg class="svg-icon"  width="18" height="18" viewBox="0 0 20 20">
                                            <path fill="red" d="M17.114,3.923h-4.589V2.427c0-0.252-0.207-0.459-0.46-0.459H7.935c-0.252,0-0.459,0.207-0.459,0.459v1.496h-4.59c-0.252,0-0.459,0.205-0.459,0.459c0,0.252,0.207,0.459,0.459,0.459h1.51v12.732c0,0.252,0.207,0.459,0.459,0.459h10.29c0.254,0,0.459-0.207,0.459-0.459V4.841h1.511c0.252,0,0.459-0.207,0.459-0.459C17.573,4.127,17.366,3.923,17.114,3.923M8.394,2.886h3.214v0.918H8.394V2.886z M14.686,17.114H5.314V4.841h9.372V17.114z M12.525,7.306v7.344c0,0.252-0.207,0.459-0.46,0.459s-0.458-0.207-0.458-0.459V7.306c0-0.254,0.205-0.459,0.458-0.459S12.525,7.051,12.525,7.306M8.394,7.306v7.344c0,0.252-0.207,0.459-0.459,0.459s-0.459-0.207-0.459-0.459V7.306c0-0.254,0.207-0.459,0.459-0.459S8.394,7.051,8.394,7.306"></path>
                                        </svg>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                  {% endif %}
              </div>
          </div>
      </div>
</div>

{% endblock %}

{% block scriptjs %}

<!--<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCnpHsl6ujM6EmvFVfoSsdLR6jxbykvw6w&callback=initMap" async defer></script>-->
<!--<script type="text/javascript" src="/static/maps/index.js"></script>-->

{%endblock %}

templates/travel/service/list.html
{% extends "../../base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Lugares</h1>
  </div>
      <div class="d-flex justify-content-end">
          <a class="btn btn-primary" href="{% url 'travel:service_add'%}"> Agregar Nuevo </a>
      </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
      <div  class="row">
          <div class="col-lg-12">
              <div class="card">
                  <div class="card-body">
                      {% if not services %}
                        <div>Aun no hay Servicios registrado</div>
                      {% else %}
                        <table class="table">
                           <thead>
                            <tr>

                                <th scope="col">Nombre del servicio</th>
                                <th scope="col">Descripcion</th>
                                <th scope="col">Costo</th>
                                <th scope="col">Acción</th>
                            </tr>
                           </thead>
                            <tbody>
                                {% for service in services %}
                                <tr>
                                <td>
                                    <a href="{% url 'travel:service_detail' slug=service.id %}">{{service.name}}</a>
                                </td>
                                <td>{{service.description}}</td>
                                <td>{{service.price}}</td>
                                <td>

                                    <a class="btn btn-small" href="{% url 'travel:service_update' slug=service.id %}"  title="Editar">
                                    <svg class="svg-icon" width="18" height="18" viewBox="0 0 20 20">
                                        <path fill="blue" d="M19.404,6.65l-5.998-5.996c-0.292-0.292-0.765-0.292-1.056,0l-2.22,2.22l-8.311,8.313l-0.003,0.001v0.003l-0.161,0.161c-0.114,0.112-0.187,0.258-0.21,0.417l-1.059,7.051c-0.035,0.233,0.044,0.47,0.21,0.639c0.143,0.14,0.333,0.219,0.528,0.219c0.038,0,0.073-0.003,0.111-0.009l7.054-1.055c0.158-0.025,0.306-0.098,0.417-0.211l8.478-8.476l2.22-2.22C19.695,7.414,19.695,6.941,19.404,6.65z M8.341,16.656l-0.989-0.99l7.258-7.258l0.989,0.99L8.341,16.656z M2.332,15.919l0.411-2.748l4.143,4.143l-2.748,0.41L2.332,15.919z M13.554,7.351L6.296,14.61l-0.849-0.848l7.259-7.258l0.423,0.424L13.554,7.351zM10.658,4.457l0.992,0.99l-7.259,7.258L3.4,11.715L10.658,4.457z M16.656,8.342l-1.517-1.517V6.823h-0.003l-0.951-0.951l-2.471-2.471l1.164-1.164l4.942,4.94L16.656,8.342z"></path>
                                    </svg>
                                    </a>
                                     <a class="btn btn-small"  title="Eliminar" href="{% url 'travel:service_delete' slug=service.id %}">
                                       <svg class="svg-icon"  width="18" height="18" viewBox="0 0 20 20">
                                            <path fill="red" d="M17.114,3.923h-4.589V2.427c0-0.252-0.207-0.459-0.46-0.459H7.935c-0.252,0-0.459,0.207-0.459,0.459v1.496h-4.59c-0.252,0-0.459,0.205-0.459,0.459c0,0.252,0.207,0.459,0.459,0.459h1.51v12.732c0,0.252,0.207,0.459,0.459,0.459h10.29c0.254,0,0.459-0.207,0.459-0.459V4.841h1.511c0.252,0,0.459-0.207,0.459-0.459C17.573,4.127,17.366,3.923,17.114,3.923M8.394,2.886h3.214v0.918H8.394V2.886z M14.686,17.114H5.314V4.841h9.372V17.114z M12.525,7.306v7.344c0,0.252-0.207,0.459-0.46,0.459s-0.458-0.207-0.458-0.459V7.306c0-0.254,0.205-0.459,0.458-0.459S12.525,7.051,12.525,7.306M8.394,7.306v7.344c0,0.252-0.207,0.459-0.459,0.459s-0.459-0.207-0.459-0.459V7.306c0-0.254,0.207-0.459,0.459-0.459S8.394,7.051,8.394,7.306"></path>
                                        </svg>
                                    </a>
                                </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                      {% endif %}
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<script>

</script>

{% endblock %}