ecommerce/apps/checkout/urls.py
from django.urls import include, path

from . import views

app_name = "checkout"

urlpatterns = [
    path("deliverychoices", views.deliverychoices, name="deliverychoices"),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

ecommerce/apps/travel/urls.py
from django.urls import path

from .views import (
    company,
    places,
    service,
    travel,
    public,
)
app_name = "travel"

urlpatterns = [

    path("",public.home,name="home_travel"),
    path("travel/user/company/", company.company_user, name="company_user"),
    path("travel/company/",company.list,name="company_list"),
    path("travel/company/add/", company.add, name="company_add"),
    path("travel/company/update/<slug:slug>/", company.update, name="company_update"),
    path("travel/company/delete/<slug:slug>/", company.delete, name="company_delete"),
    path("travel/company/<slug:slug>/detail", company.detail, name="company_detail"),


    path("travel/places/add/", places.add, name="places_add"),
    path("travel/places/update/<slug:slug>/", places.update, name="places_update"),
    path("travel/places/delete/<slug:slug>/", places.delete, name="places_delete"),
    path("travel/places/",places.list,name="places_list"),
    path("travel/places/<slug:slug>/detail", places.detail, name="places_detail"),

    path("travel/service/add/", service.add, name="service_add"),
    path("travel/service/<slug:slug>/detail", service.detail, name="service_detail"),
    path("travel/service/update/<slug:slug>/", service.update, name="service_update"),
    path("travel/service/delete/<slug:slug>/", service.delete, name="service_delete"),
    path("travel/service/", service.list, name="service_list"),

    path("travel/service/<str:service_id>/travel/add/", travel.add, name="travel_add"),
    path("travel/service/<str:service_id>/travel/<slug:slug>/detail", travel.detail, name="travel_detail"),
    path("travel/service/<str:service_id>/travel/update/<slug:slug>/", travel.update, name="travel_update"),
    path("travel/service/<str:service_id>/travel/delete/<slug:slug>/", travel.delete, name="travel_delete"),
    path("travel/service/<str:service_id>/travel/", travel.list, name="travel_list"),

    # path("mycompany",views.CompanyView.as_view(),name="mycompany"),
    # path("<slug:slug>", views.product_detail, name="product_detail"),
    # path("shop/<slug:category_slug>/", views.category_list, name="category_list"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ecommerce.apps.travel.urls", namespace="travel")),
    path("", include("ecommerce.apps.catalogue.urls", namespace="catalogue")),
    path("checkout/", include("ecommerce.apps.checkout.urls", namespace="checkout")),
    path("basket/", include("ecommerce.apps.basket.urls", namespace="basket")),
    path("account/", include("ecommerce.apps.account.urls", namespace="account")),
    path("orders/", include("ecommerce.apps.orders.urls", namespace="orders")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce/apps/travel/views/company.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Company
from ..forms import CompanyForm
from django.contrib.auth.decorators import login_required
from django.views import View


from django.http import HttpResponse
@login_required
def company_user(request):
    try:
        company  = request.user.company
        return render(request, "travel/company/company.html", {"company": company,"services": company.services.all()})
    except Company.DoesNotExist:
        company = None
    return render(request, "travel/company/company.html", {"company": False ,"services": [] })


@login_required
def add(request):
    if request.method == "POST":
        company_form = CompanyForm(data=request.POST)
        if company_form.is_valid():
            company = company_form.save(commit=False)
            company.user = request.user
            company.save()
            return HttpResponseRedirect(reverse("travel:company_user"))
        else:
            return render(request, "travel/company/add.html", {"form": company_form})
    company_form = CompanyForm()
    return render(request,"travel/company/add.html",{"form": company_form})


@login_required
def update(request,slug=None):
    company = get_object_or_404(Company, id=slug)
    if request.method == "POST":
        company_form = CompanyForm(data=request.POST,instance=company)
        if company_form.is_valid():
            company_form.save()
            return HttpResponseRedirect(reverse("travel:company_user"))
        else:
            return render(request,"travel/company/update.html",{"form": company_form ,'company':company})

    company_form = CompanyForm(instance=company)
    return render(request,"travel/company/update.html",{"form": company_form ,'company':company})

@login_required
def detail(request,slug):
    company = get_object_or_404(Company, id=slug)
    return render(request, "travel/company/company.html", {"company": company, "services": company.services.all()})


@login_required
def delete(request,slug):
    company = get_object_or_404(Company, id=slug)
    if request.method == "POST":
        company.delete()
        return render(request,"travel/company/delete.html")
    return render(request, "travel/company/delete.html", {"company":company})


@login_required
def list(request):
    companies = Company.objects.all().order_by("name")
    return render(request,"travel/company/list.html",{"companies": companies})

ecommerce/apps/travel/views/places.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Place
from ..forms import PlaceForm
from django.contrib.auth.decorators import login_required

@login_required
def add(request):
    if request.method == "POST":
        place_form = PlaceForm(request.POST, request.FILES)
        if place_form.is_valid():
            place_form.save()
            return HttpResponseRedirect(reverse("travel:places_list"))
        else:
            return render(request, "travel/places/add.html", {"form": place_form})
    place_form = PlaceForm()
    return render(request,"travel/places/add.html",{"form": place_form})


@login_required
def update(request,slug=None):
    place = get_object_or_404(Place, id=slug)
    if request.method == "POST":
        place_form = PlaceForm(data=request.POST,files=request.FILES,instance=place)
        if place_form.is_valid():
            place_form.save()
            return HttpResponseRedirect(reverse("travel:places_list"))
        else:
            return render(request,"travel/places/update.html",{"form": place_form ,'place':place})

    place_form = PlaceForm(instance=place)
    return render(request,"travel/places/update.html",{"form": place_form ,'place':place})

@login_required
def detail(request,slug):
    place = get_object_or_404(Place, id=slug)
    return render(request, "travel/places/detail.html", {"place": place})


@login_required
def delete(request,slug):
    place = get_object_or_404(Place, id=slug)
    if request.method == "POST":
        place.delete()
        return render(request,"travel/places/delete.html")
    return render(request, "travel/places/delete.html", {"place":place})


@login_required
def list(request):
    places = Place.objects.all().order_by("name")
    return render(request,"travel/places/list.html",{"places": places})

ecommerce/apps/travel/views/public.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Service,Travel
from ..forms import TravelForm
from django.contrib.auth.decorators import login_required


def home(request):
    services = Service.objects.all().order_by("name")
    return render(request,"public/travel/home.html",{"services": services})

ecommerce/apps/travel/views/service.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Service
from ..forms import ServiceForm
from django.contrib.auth.decorators import login_required

@login_required
def add(request):
    if request.method == "POST":
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            service = form.save(commit=False)
            service.company = request.user.company
            service.save()
            return HttpResponseRedirect(reverse("travel:company_user"))
        else:
            return render(request, "travel/service/add.html", {"form": form})
    form = ServiceForm()
    return render(request,"travel/service/add.html",{"form": form})

@login_required
def detail(request,slug):
    service = get_object_or_404(Service,id=slug)
    return render(request,"travel/service/detail.html",{"service": service,"travels":service.travels.all()})



@login_required
def update(request,slug):

    service = get_object_or_404(Service,id=slug,company=request.user.company)
    if request.method == "POST":
        form = ServiceForm(request.POST, request.FILES,instance=service)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("travel:service_detail",kwargs={'slug':service.id}))
        else:
            return render(request, "travel/service/update.html", {"form": form , "service":service})
    form = ServiceForm(instance=service)
    return render(request,"travel/service/update.html",{"form": form , "service":service})


@login_required
def delete(request,slug):
    service = get_object_or_404(Service, id=slug)
    if request.method == "POST":
        service.delete()
        return render(request, "travel/service/delete.html")
    return render(request, "travel/service/delete.html", {"service":service})



@login_required
def list(request):
    services = Service.objects.all().order_by("name")
    return render(request,"travel/service/list.html",{"services": services})

ecommerce/apps/travel/views/travel.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from ..models import Service,Travel
from ..forms import TravelForm
from django.contrib.auth.decorators import login_required
import datetime
@login_required
def add(request,service_id):
    service = get_object_or_404(Service,id=service_id)
    if request.method == "POST":
        form = TravelForm(request.POST, request.FILES)
        if form.is_valid():
            travel = form.save(commit=False)
            travel.available_seats = travel.passengers_limit
            travel.save()
            return HttpResponseRedirect(reverse("travel:service_detail" , kwargs={'slug':service.id}))
        else:
            return render(request, "travel/travel/add.html", {"form": form , "service":service})

    travel = Travel(
        service = service ,
        time_departure = datetime.date.today ,
        time_arrival_destination = datetime.date.today ,
        time_departure_return = datetime.date.today ,
        time_arrival_return =  datetime.date.today,
        travel_type = "V" ,
        passengers_limit = 100 ,
    )
    form = TravelForm(instance=travel)
    return render(request,"travel/travel/add.html",{"form": form , "service":service})

@login_required
def detail(request,slug,service_id):
    service = get_object_or_404(Service,id=service_id)
    travel = get_object_or_404(Travel,id=slug)
    return render(request,"travel/travel/detail.html",{"travel": travel,"service":service})



@login_required
def update(request,slug,service_id):
    service = get_object_or_404(Service,id=service_id)
    travel = get_object_or_404(Travel,id=slug,service=service)
    if request.method == "POST":
        form = TravelForm(request.POST, request.FILES,instance=travel)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("travel:travel_detail",kwargs={'slug':travel.id,'service_id':service.id }))
        else:
            return render(request,"travel/travel/update.html",{"form": form , "travel":travel,"service":service })
    form = TravelForm(instance=travel)
    return render(request,"travel/travel/update.html",{"form": form , "travel":travel,"service":service })


@login_required
def delete(request,slug,service_id):
    service = get_object_or_404(Service, id=service_id)
    travel = get_object_or_404(Travel, id=slug)
    if request.method == "POST":
        travel.delete()
        return render(request, "travel/travel/delete.html")
    return render(request, "travel/travel/delete.html", {"travel":travel,"service":service })



@login_required
def list(request):
    travels = Travel.objects.all().order_by("name")
    return render(request,"travel/travel/list.html",{"travels": travels})

templates/travel/company/base.html
{% extends "../../base.html" %}
{% load static %}
{% block title %}Nueva empresa{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Tu empresa</h1>
  </div>
<!--  <div class="col-12">-->
<!--    <p>Manage your <b>items</b> in your basket</p>-->
<!--  </div>-->
  <hr />
</div>

<div class="container">
  <div class="login d-flex align-items-center">
    <div class="col-12 col-md-12 col-lg-12 mx-auto">
      {% block sub_content %}
      {% endblock %}
    </div>
  </div>
</div>


<script>

</script>

{% endblock %}

templates/travel/company/company.html
{% extends "../../base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Tu empresa</h1>
  </div>
<!--  <div class="col-12">-->
<!--    <p>Manage your <b>items</b> in your basket</p>-->
<!--  </div>-->
  <hr />
</div>

<div class="container">
  <div class="row g-3">
    {% if not company %}
    <div class="col-12">Usted no tiene una empresa de trasporte turistico.
        <a class="btn btn-primary" href="{% url 'travel:company_add' %}">Registrar mi empresa</a>
    </div>
      {% else %}

      <div  class="row">
          <div class="col-lg-12">
              <div class="card">
                  <card class="card-body">

                      <div class="d-flex justify-content-end">

                          <a class="nav-link dropdown-toggle text-reset" href="#" id="companyDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                              <svg class="svg-icon" width="22" height="22" viewBox="0 0 20 20">
							    <path d="M3.936,7.979c-1.116,0-2.021,0.905-2.021,2.021s0.905,2.021,2.021,2.021S5.957,11.116,5.957,10
								S5.052,7.979,3.936,7.979z M3.936,11.011c-0.558,0-1.011-0.452-1.011-1.011s0.453-1.011,1.011-1.011S4.946,9.441,4.946,10
								S4.494,11.011,3.936,11.011z M16.064,7.979c-1.116,0-2.021,0.905-2.021,2.021s0.905,2.021,2.021,2.021s2.021-0.905,2.021-2.021
								S17.181,7.979,16.064,7.979z M16.064,11.011c-0.559,0-1.011-0.452-1.011-1.011s0.452-1.011,1.011-1.011S17.075,9.441,17.075,10
								S16.623,11.011,16.064,11.011z M10,7.979c-1.116,0-2.021,0.905-2.021,2.021S8.884,12.021,10,12.021s2.021-0.905,2.021-2.021
								S11.116,7.979,10,7.979z M10,11.011c-0.558,0-1.011-0.452-1.011-1.011S9.442,8.989,10,8.989S11.011,9.441,11.011,10
								S10.558,11.011,10,11.011z"></path>
						    </svg>
                          </a>
                           <div class="dropdown-menu rounded-0" aria-labelledby="companyDropdown">
                            <div class="card border-0">
                              <div class="card-body">
                                <ul class="list-group list-group-flush dropdown-account-link">
                                    <a href="{% url 'travel:company_update' slug=company.id %}" class="text-reset small list-group-item p-0 pb-O border-0 dropdown-account-link">Actualizar</a>
                                </ul>
                              </div>
                            </div>
                           </div>
                      </div>

                      <div class="">
                          <h1>{{company.name}}</h1>
                          <br>
                          <span>
                             Razon Social: {{company.razon_social}}
                          </span>
                          <br>
                          <span>
                              NIT: {{company.nit}}
                          </span>
                      </div>

                       <div class="d-flex justify-content-end">
                         <svg class="svg-icon" width="100" height="100" viewBox="0 0 20 20">
                             <path d="M12.173,16.086c0.72,0,1.304-0.584,1.304-1.305V6.089c0-0.72-0.584-1.304-1.304-1.304c-0.721,0-1.305,0.584-1.305,1.304v8.692C10.868,15.502,11.452,16.086,12.173,16.086z M11.738,6.089c0-0.24,0.194-0.435,0.435-0.435s0.435,0.194,0.435,0.435v8.692c0,0.24-0.194,0.436-0.435,0.436s-0.435-0.195-0.435-0.436V6.089zM16.52,16.086c0.72,0,1.304-0.584,1.304-1.305v-11.3c0-0.72-0.584-1.304-1.304-1.304c-0.721,0-1.305,0.584-1.305,1.304v11.3C15.215,15.502,15.799,16.086,16.52,16.086z M16.085,3.481c0-0.24,0.194-0.435,0.435-0.435s0.435,0.195,0.435,0.435v11.3c0,0.24-0.194,0.436-0.435,0.436s-0.435-0.195-0.435-0.436V3.481z M3.48,16.086c0.72,0,1.304-0.584,1.304-1.305v-3.477c0-0.72-0.584-1.304-1.304-1.304c-0.72,0-1.304,0.584-1.304,1.304v3.477C2.176,15.502,2.76,16.086,3.48,16.086z M3.045,11.305c0-0.24,0.194-0.435,0.435-0.435c0.24,0,0.435,0.194,0.435,0.435v3.477c0,0.24-0.195,0.436-0.435,0.436c-0.24,0-0.435-0.195-0.435-0.436V11.305z M18.258,16.955H1.741c-0.24,0-0.435,0.194-0.435,0.435s0.194,0.435,0.435,0.435h16.517c0.24,0,0.435-0.194,0.435-0.435S18.498,16.955,18.258,16.955z M7.826,16.086c0.72,0,1.304-0.584,1.304-1.305V8.696c0-0.72-0.584-1.304-1.304-1.304S6.522,7.977,6.522,8.696v6.085C6.522,15.502,7.106,16.086,7.826,16.086z M7.392,8.696c0-0.239,0.194-0.435,0.435-0.435s0.435,0.195,0.435,0.435v6.085c0,0.24-0.194,0.436-0.435,0.436s-0.435-0.195-0.435-0.436V8.696z"></path>
                         </svg>
                      </div>



                  </card>
              </div>
          </div>
      </div>


      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

          {% for service in services %}
          <div class="col">
              <div class="card card-service">

                  <div>
                      <img src="/media/{{service.img_l}}" class="card-img-top" alt="...">
                      <div class="card-service-title ">
                          <a href="{% url 'travel:service_detail'  slug=service.id %}"  class="text-light" style="text-decoration:none;">{{service.name}}</a>
                      </div>
                  </div>

                  <div class="card-body">
                      {{service.description}}
                  </div>
                    <div class="card-footer">
                      {{service.price}}$ por persona
<!--                        <a href="#" class="btn btn-primary btn-small"> Reservar</a>-->
                  </div>
              </div>
          </div>
          {% endfor %}







          <div class="col">
            <a href="{% url 'travel:service_add' %}" class="text-reset text-decoration-none" role="button" style="max-width: 540px;">
              <div class="card mb-3">
                <div class="row g-0">
                  <div class="col-2 position-relative">
                        <span style="font-size:50px; margin-left:20px;">+</span>
                  </div>
                  <div class="col-10">
                    <div class="card-body ps-0 ps-md-1">
                      <h1 class="h5">Agregar</h1>
                      <p class="card-text small text-muted">Nuevo servicio de viaje</p>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
      </div>


    {% endif %}


<!--    <div class="col-12 bg-light p-3 d-flex justify-content-between">-->
<!--      <div class="d-flex d-flex-inline">-->
<!--        <div class="pe-3">Order</div>-->
<!--        <div class="dropdown">-->
<!--          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink"-->
<!--            data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Shipping options-->
<!--            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"-->
<!--              class="bi bi-chevron-down" viewBox="0 0 16 16">-->
<!--              <path fill-rule="evenodd"-->
<!--                d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />-->
<!--            </svg>-->
<!--          </a>-->
<!--          <ul class="dropdown-menu" aria-labelledby="dropdownLink">-->
<!--            <li class="item small">Next day delivery</li>-->
<!--            <li class="item small">Premimum delivery</li>-->
<!--          </ul>-->
<!--        </div>-->
<!--      </div>-->
<!--      <div class="text-end">-->
<!--        <div class="">Sub Total: <span class="fw-bold">£</span>-->
<!--          <div id="subtotal" class="d-inline-flex fw-bold">{{basket.get_subtotal_price}}</div>-->
<!--        </div>-->
<!--        <div id="">Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold">£11.50</span></div>-->
<!--        <div class="pt-2">Total to pay: <span class="fw-bold h5">£</span><span id="total"-->
<!--            class="fw-bold h5">{{basket.get_total_price}}</span></div>-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">-->
<!--      <div class="d-grid gap-2 ">-->
<!--        <a role="button" href="{% url 'checkout:deliverychoices' %}" class="btn btn-success fw-bold" type="button">Checkout Securely</a>-->
<!--        <button class="btn btn-light" type="button">Save for later</button>-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class="col-md-7 col-lg-8 p-0">-->
<!--&lt;!&ndash;      {% for item in basket %}&ndash;&gt;-->
<!--&lt;!&ndash;      {% with product=item.product %}&ndash;&gt;-->
<!--      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">-->
<!--        <div class="row g-0">-->
<!--          <div class="col-md-2 d-none d-md-block">-->
<!--&lt;!&ndash;            {% for image in product.product_image.all %}&ndash;&gt;-->
<!--&lt;!&ndash;            {% if image.is_feature%}&ndash;&gt;-->
<!--            <img class="img-fluid" alt="Responsive image" src="{{ image.image.url }}" alt="{{ image.image.alt_text }}">-->
<!--&lt;!&ndash;            {% endif %}&ndash;&gt;-->
<!--&lt;!&ndash;            {% endfor %}&ndash;&gt;-->
<!--          </div>-->
<!--          <div class="col-md-10 ps-md-3">-->
<!--            <div class="card-body p-1">-->
<!--              <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">-->
<!--                <p class="card-text pb-3">{{product.title}}</p>-->
<!--              </a>-->
<!--              <label for="select">Qty</label>-->
<!--              <select id="select{{product.id}}" style="width:50px;height:31px;">-->
<!--                <option value="" selected disabled hidden>{{item.qty}}</option>-->
<!--                <option value="">1</option>-->
<!--                <option value="">2</option>-->
<!--                <option value="">3</option>-->
<!--                <option value="">4</option>-->
<!--              </select>-->
<!--              <a type="button" id="update-button" data-index="{{product.id}}"-->
<!--                class="update-button text-decoration-none small ps-3">Update</a>-->
<!--              <a type="button" id="delete-button" data-index="{{product.id}}"-->
<!--                class="delete-button text-decoration-none small">Delete</a>-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--&lt;!&ndash;      {% endwith %}&ndash;&gt;-->
<!--&lt;!&ndash;      {% endfor %}&ndash;&gt;-->
<!--    </div>-->

  </div>
</div>

<script>

</script>

{% endblock %}

templates/travel/company/list.html
{% extends "../../base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Empresas de Transporte</h1>
  </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
      <div  class="row">
          <div class="col-lg-12">
              <div class="card">
                  <div class="card-body">
                      {% if not companies %}
                        <div>Aun no hay registrado ninguna empresa</div>
                      {% else %}
                        <table class="table">
                           <thead>
                            <tr>

                                <th scope="col">Nombre Empresa</th>
                                <th scope="col">Razon Social</th>
                                <th scope="col">NIT</th>
                                <th scope="col">Propietario</th>
                                <th scope="col">Accion</th>
                            </tr>
                           </thead>
                            <tbody>
                                {% for company in companies %}
                                <tr>
                                <td>
                                    <a href="{% url 'travel:company_detail' slug=company.id %}">{{company.name}}</a>
                                </td>
                                <td>{{company.razon_social}}</td>
                                <td>{{company.nit}}</td>
                                <td>{{company.user.full_name}}</td>

                                <td>
                                    <a class="btn btn-small" href="{% url 'travel:company_update' slug=company.id %}"  title="Editar">
                                    <svg class="svg-icon" width="18" height="18" viewBox="0 0 20 20">
                                        <path fill="blue" d="M19.404,6.65l-5.998-5.996c-0.292-0.292-0.765-0.292-1.056,0l-2.22,2.22l-8.311,8.313l-0.003,0.001v0.003l-0.161,0.161c-0.114,0.112-0.187,0.258-0.21,0.417l-1.059,7.051c-0.035,0.233,0.044,0.47,0.21,0.639c0.143,0.14,0.333,0.219,0.528,0.219c0.038,0,0.073-0.003,0.111-0.009l7.054-1.055c0.158-0.025,0.306-0.098,0.417-0.211l8.478-8.476l2.22-2.22C19.695,7.414,19.695,6.941,19.404,6.65z M8.341,16.656l-0.989-0.99l7.258-7.258l0.989,0.99L8.341,16.656z M2.332,15.919l0.411-2.748l4.143,4.143l-2.748,0.41L2.332,15.919z M13.554,7.351L6.296,14.61l-0.849-0.848l7.259-7.258l0.423,0.424L13.554,7.351zM10.658,4.457l0.992,0.99l-7.259,7.258L3.4,11.715L10.658,4.457z M16.656,8.342l-1.517-1.517V6.823h-0.003l-0.951-0.951l-2.471-2.471l1.164-1.164l4.942,4.94L16.656,8.342z"></path>
                                    </svg>
                                    </a>
                                     <a class="btn btn-small"  title="Eliminar" href="{% url 'travel:company_delete' slug=company.id %}">
                                       <svg class="svg-icon"  width="18" height="18" viewBox="0 0 20 20">
                                            <path fill="red" d="M17.114,3.923h-4.589V2.427c0-0.252-0.207-0.459-0.46-0.459H7.935c-0.252,0-0.459,0.207-0.459,0.459v1.496h-4.59c-0.252,0-0.459,0.205-0.459,0.459c0,0.252,0.207,0.459,0.459,0.459h1.51v12.732c0,0.252,0.207,0.459,0.459,0.459h10.29c0.254,0,0.459-0.207,0.459-0.459V4.841h1.511c0.252,0,0.459-0.207,0.459-0.459C17.573,4.127,17.366,3.923,17.114,3.923M8.394,2.886h3.214v0.918H8.394V2.886z M14.686,17.114H5.314V4.841h9.372V17.114z M12.525,7.306v7.344c0,0.252-0.207,0.459-0.46,0.459s-0.458-0.207-0.458-0.459V7.306c0-0.254,0.205-0.459,0.458-0.459S12.525,7.051,12.525,7.306M8.394,7.306v7.344c0,0.252-0.207,0.459-0.459,0.459s-0.459-0.207-0.459-0.459V7.306c0-0.254,0.207-0.459,0.459-0.459S8.394,7.051,8.394,7.306"></path>
                                        </svg>
                                    </a>
                                </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                      {% endif %}
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

<script>

</script>

{% endblock %}