ecommerce/apps/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

ecommerce/apps/basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

ecommerce/apps/travel/urls.py
from django.urls import path

from .views import (
    company,
    places,
    service,
    travel,
    public,
)
app_name = "travel"

urlpatterns = [

    path("",public.home,name="home_travel"),
    path("travel/user/company/", company.company_user, name="company_user"),
    path("travel/company/",company.list,name="company_list"),
    path("travel/company/add/", company.add, name="company_add"),
    path("travel/company/update/<slug:slug>/", company.update, name="company_update"),
    path("travel/company/delete/<slug:slug>/", company.delete, name="company_delete"),
    path("travel/company/<slug:slug>/detail", company.detail, name="company_detail"),


    path("travel/places/add/", places.add, name="places_add"),
    path("travel/places/update/<slug:slug>/", places.update, name="places_update"),
    path("travel/places/delete/<slug:slug>/", places.delete, name="places_delete"),
    path("travel/places/",places.list,name="places_list"),
    path("travel/places/<slug:slug>/detail", places.detail, name="places_detail"),

    path("travel/service/add/", service.add, name="service_add"),
    path("travel/service/<slug:slug>/detail", service.detail, name="service_detail"),
    path("travel/service/update/<slug:slug>/", service.update, name="service_update"),
    path("travel/service/delete/<slug:slug>/", service.delete, name="service_delete"),
    path("travel/service/", service.list, name="service_list"),

    path("travel/service/<str:service_id>/travel/add/", travel.add, name="travel_add"),
    path("travel/service/<str:service_id>/travel/<slug:slug>/detail", travel.detail, name="travel_detail"),
    path("travel/service/<str:service_id>/travel/update/<slug:slug>/", travel.update, name="travel_update"),
    path("travel/service/<str:service_id>/travel/delete/<slug:slug>/", travel.delete, name="travel_delete"),
    path("travel/service/<str:service_id>/travel/", travel.list, name="travel_list"),

    # path("mycompany",views.CompanyView.as_view(),name="mycompany"),
    # path("<slug:slug>", views.product_detail, name="product_detail"),
    # path("shop/<slug:category_slug>/", views.category_list, name="category_list"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ecommerce.apps.travel.urls", namespace="travel")),
    path("", include("ecommerce.apps.catalogue.urls", namespace="catalogue")),
    path("checkout/", include("ecommerce.apps.checkout.urls", namespace="checkout")),
    path("basket/", include("ecommerce.apps.basket.urls", namespace="basket")),
    path("account/", include("ecommerce.apps.account.urls", namespace="account")),
    path("orders/", include("ecommerce.apps.orders.urls", namespace="orders")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>{% block title %}Mi Transporte {% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
  </script>

  <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
  <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">


  <style>
  	#map {
        height: 100%;
        }
</style>
</head>

<body>
  <header class="pb-3">
    <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
      <div class="container-fluid px-md-4">
        <div class="d-flex w-100 navbar-collapse">
          <a class="navbar-brand d-flex-inline" href="/">

             <svg class="svg-icon" width="28" height="28" viewBox="0 0 20 20">
               <path d="M10,1.375c-3.17,0-5.75,2.548-5.75,5.682c0,6.685,5.259,11.276,5.483,11.469c0.152,0.132,0.382,0.132,0.534,0c0.224-0.193,5.481-4.784,5.483-11.469C15.75,3.923,13.171,1.375,10,1.375 M10,17.653c-1.064-1.024-4.929-5.127-4.929-10.596c0-2.68,2.212-4.861,4.929-4.861s4.929,2.181,4.929,4.861C14.927,12.518,11.063,16.627,10,17.653 M10,3.839c-1.815,0-3.286,1.47-3.286,3.286s1.47,3.286,3.286,3.286s3.286-1.47,3.286-3.286S11.815,3.839,10,3.839 M10,9.589c-1.359,0-2.464-1.105-2.464-2.464S8.641,4.661,10,4.661s2.464,1.105,2.464,2.464S11.359,9.589,10,9.589"></path>
             </svg>
            MiPaseo

          </a>
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
                Todos
                <i class="ps-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-chevron-down" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                  </svg></i>
              </a>
              <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Todos</a></li>
              </ul>
            </li>
          </ul>
          <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
            aria-label="Toggle navigation">
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-list"
                viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                  d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
              </svg>
            </div>
            <span class="fs15 fw500">Menu</span>
          </button>
          <div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent2">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle text-reset" href="#" id="navbarDropdown" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">

                      {% if user.is_authenticated %}
                     <div class="small text-muted">
                        Hola,
                        {{ request.user.full_name }}
                     </div>
                      <span class="fs15 fw500">{{ request.user.get_type_user}}</span>

                      {% else %}
                      Iniciar sesión
                      {% endif %}


                    </span>
                  </a>
                  <div class="dropdown-menu rounded-0" aria-labelledby="navbarDropdown">
                    <div class="card border-0">
                      <div class="card-body">
                        <h6 class="card-title"></h6>
                        <ul class="list-group list-group-flush dropdown-account-link">
                          {% if user.is_authenticated %}
                          <a href="{% url "account:dashboard" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Mi perfil</a>
                          <a href="{% url "travel:company_user" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Mi Empresa</a>
                          <a href="{% url "travel:places_list" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Lugares</a>

                          <a href="#" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Orders</a>
                          <a href="{% url "account:logout" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Salir</a>
                          {% else %}
                          <a href="{% url "account:login" %}" class="text-reset small list-group-item p-0 pb-1 border-0 dropdown-account-link">Iniciar sesion</a>
                          {% endif %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <a type="button" role="button" href="{% url "basket:basket_summary" %}"
            class="btn btn-outline-secondary border-0 basket-btn">
            {% with total_qty=basket|length %}
            <div id="basket-qty" class="basket-qty">
              {% if total_qty > 0 %}
              {{ total_qty }}
              {% else %}
              0
              {% endif %}
            </div>
            {% endwith %}
            <div>
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-cart3"
                viewBox="0 0 16 16">
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
              </svg>
            </div>
            <span class="fs15 fw500">Viajes</span>
          </a>
        </div>
        <div class="d-md-none d-lg-none d-xl-none">
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">


            </ul>
            <h6 class="card-title">Mi cuenta</h6>
              <ul class="list-group list-group-flush dropdown-account-link">
                {% if user.is_authenticated %}
                <a href="{% url "account:dashboard" %}" class="dropdown-item">Tu cuenta</a>
                <a href="#" class="dropdown-item">Orders</a>
                <a href="{% url "account:logout" %}" class="dropdown-item">Salir </a>
                {% else %}
                <a href="{% url "account:login" %}" class="dropdown-item">Inicio de Sesion</a>
                {% endif %}
              </ul>
          </div>
        </div>
        <form class="d-flex w-100 d-md-none">
          <input class="form-control me-2" type="search" placeholder="Viajes o Preguntas frecuentes" aria-label="Search">
          <button class="btn btn-outline-secondary" type="submit">Buscar</button>
        </form>
      </div>
    </nav>
  </header>

  <main class="pt-5">
    <div id="content">{% block content %} {% endblock %}</div>
  </main>

  <footer class="container py-5 footer">
    <hr>
    <div class="row pt-4">
      <div class="col-12 col-md">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-asterisk"
          viewBox="0 0 16 16">
          <path
            d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
        </svg>
        <small class="d-block mb-3 text-muted">&copy; Semestre I - 2022</small>
      </div>
      <div class="col-6 col-md fs15">
        <h5>Viajes a</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">La Paz</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Oruro</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Cochabanba</a></li>

        </ul>
      </div>
      <div class="col-6 col-md fs15">
        <h5>Automoviles</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">Jeeps</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Taxis</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Bus Turistico</a></li>
        </ul>
      </div>
      <div class="col-6 col-md fs15">
        <h5>Servicios</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">Business</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Education</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Government</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Gaming</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Acerca de nosotros</h5>
        <ul class="list-unstyled">
          <li><a class="link-secondary text-decoration-none" href="#">Team</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Locations</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Privacy</a></li>
          <li><a class="link-secondary text-decoration-none" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>

    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="mi-modal">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
          </div>
          <div class="modal-body"><p></p></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" id="modal-btn-si">Si</button>
            <button type="button" class="btn btn-primary" id="modal-btn-no">No</button>
          </div>
        </div>
      </div>
    </div>
<!--  <button class="btn btn-default" id="btn-confirm" onclick="md(d,'url','mensaje')">Confirm</button>-->

  <script>

    confirmationDelete = d = function(confirm,url){
      if(confirm){
        $.post( url , function( data ) {
         location.reload();
        }).fail(function(data) {
         console.log( "Ha ocurrido un error" )
        });
      }
    }

    var md = function(callback,url,msj){
      $("#mi-modal").modal('show');
      var modal =  $("#mi-modal");
      modal.find('.modal-body p').text('¿Esta seguro de borrar?');
      modal.find('.modal-header h4').html(msj);

      $("#modal-btn-si").on("click", function(){
        callback(true,url);
        $("#mi-modal").modal('hide');
      });
      $("#modal-btn-no").on("click", function(){
        callback(false);
        $("#mi-modal").modal('hide');
      });
    };

    var ow = openWindow= function( url ){
      window.open(url, '_blank', 'location=yes,height=700,width=900,scrollbars=yes,status=yes');
    }

  </script>


  {% block scriptjs %} {% endblock %}

</body>

</html>